package com.shersoft.aliroom.Utility

import android.os.Bundle

object Constants {
    const val nb_txt_network =
        "Yout App is not Configured With Server.\t Please Check your Network Connectivity"
    const val KOTNO = "KOTNO"
    const val WAITER = "WAITER"
    const val ISFIRSTTIMEKEY = "ISFIRSTTIME"
    var TYPECOUNT = 0
    var ISFIRSTTIME = true
    const val GROUND_PRINT = 0
    const val FLOOR_PRINT = 1
    var FLOOR_Value = 1
    const val TABLE = "TABLE"
    const val PBKEY = "PBKEY"
    const val SECTION = "SECTION"
    const val PASSWORD = "PASSWORD"
    const val WAITERMODEL = "WAITERMODEL"
    const val ADMIN = "ADMIN"
    const val BILLNO = "BILLNO"

    const val INCORRECT_UPA = "Incorrect Username or Password!"
    const val ISCONNECTED = "Check Your Connection Wi-Fi&IP"
    const val EMPTYFIELD = "Empty Field PleaseFill"
    const val ITEMADDED = "Item Added Succesfully"
    const val PLEASCAT = "Please Select Catagroy"
    const val ALREXIST = "Already Exist"
    const val AC = "AC"
    const val NONAC = "NON-AC"
    const val ACDELUX = "AC-DELUX"
    const val PARCEL = "PARCEL"
    const val CLOSED = "CLOSED"
    const val OPEN = "OPEN"
    const val TYPE = "TYPE"
    var TYPE_VALUE = ""
    const val MSHAREDATA = "MSHAREDATA"
    const val MNHAREDATA = "MNSHAREDATA"
    const val GROUPNAME = "GROUPNAME"
    const val ISWAITER = "ISWAITER"
    const val KBLIST = "KBLIST"
    const val TTYPE = "TTYPE"
    var bundle = Bundle()
    const val SMWRONG = "Some thing went Wrong"
    const val SMWRONGW = "Went Wrong May Another Waiter Added it"
    const val BILADD = "Bill Added"
    const val ISTABLETAKEN = "ISTABLETAKEN"
    const val ALLREADYTABLE = "This Table already takenby"
    const val STATUSUPDATED = "Status updated"
    const val AC_BTN = "ACBTN"
    const val ACD_BTN = "ACDBTN"
    const val PARCEL_BTN = "PARCELBTN"
    const val NONAC_BTN = "NONACBTN"
    const val DPLEFILL = "Please Select date"
    const val DFORMATERR = "Date Format Error eg-: 2020-12-28"
    const val SELECTPW = "Select appropriate item"
    const val OPFRAG = "OPFRAG"
    const val OPFRAGDETA = "OPFRAGDETA"
    var STATUSFRGREP = OPFRAG
    const val TODAY = "TODAY"
    const val YESTERDAY = "YESTERDAY"
    val ISPRINTERENABLE: String? = "ISPRINTERENABLE"
    val PRINTERMODEL: String? = "PRINTERMODEL"
    val PRINTERTYPE: String? = "PRINTERTYPE"
    val PRINTERIP: String? = "PRINTERIP"
    val PRINTERPORT: String? = "PRINTERPORT"
    const val CONTENT_THE = "CONTENT"
    const val TOTAL_THE = "TOTAL"
    const val HEAD_THE = "HEAD"
    val CAPTAIN: String? = "CAPTAIN"
    //    kotkitchen status
    const val DEFAULT = "Y"
    const val SEEN = "S"
    const val WAIT = "W"
    const val DELIVERD = "D"
    const val KITCHEN = "KITCHEN"
    const val KITCHENCATEGORY = "KITCHENCATEGORY"
    val ISKITCHEN: String? = "ISKITCHEN"
    const val SIM1 = "SIM1"
    val BUNDLE: String? = "BUNDLE"
    val DATACOUNT: String? = "DATACOUNT"
    //BackgroundService
    const val ACTION_FOO = "com.shersoft.Sherhotel.Service.action.FOO"
    const val ACTION_BAZ = "com.shersoft.Sherhotel.Service.action.BAZ"
    // TODO: Rename parameters
    const val EXTRA_PARAM1 = "com.shersoft.Sherhotel.Service.extra.PARAM1"
    const val EXTRA_PARAM2 = "com.shersoft.Sherhotel.Service.extra.PARAM2"

    //generalsettings
    const val COMPANYNAME = "COMPANYNAME"
    val ISKITCHEN1: String? = "ISKITCHEN1"
    const val ENABLEBUTTON = "ENABLE BUTTON"
    const val LoadController = "LoadController"
    val ISADMIN: String? = "ISADMIN"
    const val ABOUTUS = "ABOUTUS"
    val DATABASENAME_Ali: String? = "Alidatabase"
    const val TABLENAME_SALETABLE = "TABLENAME_SALETABLE"
    const val TABLENAME_ADDSTOCK = "TABLENAME_ADDSTOCK"
    const val TABLENAME_PURCHASELIST = "TABLENAME_PURCHASELIST"
    //column
    const val COLUMN_STOCK_PRODUCTNAME = "PRODUCTNAME"
    const val COLUMN_STOCK_STOCKQUANTITY = "STOCKQUANTITY"
    const val COLUMN_STOCK_ACTUALPRICE = "ACTUALPRICE"
    const val COLUMN_STOCK_SPECIFICATION = "SPECIFICATION"
    const val COLUMN_STOCK_IAMGE = "IAMGE"
    const val COLUMN_STOCK_VAT5 = "VAT5"
    const val COLUMN_STOCK_NETAMOUNT = "NETAMOUNT"
    const val COLUMN_STOCK_ID = "id"

    const val COLUMN_PURCHASE_PURCHASEDATE = "PURCHASEDATE"
    const val COLUMN_PURCHASE_COMPANYNAME = "COMPANYNAME"
    const val COLUMN_PURCHASE_ACTUALAMOUNT = "ACTUALAMOUNT"
    const val COLUMN_PURCHASE_VAT5 = "VAT5"
    const val COLUMN_PURCHASE_NETAMOUNT = "NETAMOUNT"
    const val COLUMN_PURCHASE_ID = "id"

    const val COLUMN_SALE_ID = "id"
    const val COLUMN_SALE_DATE = "DATE"
    const val COLUMN_SALE_CUSTOMERNAME = "CUSTOMERNAME"
    const val COLUMN_SALE_MOBILENO = "MOBILENO"
    const val COLUMN_SALE_PRODUCT = "PRODUCT"
    const val COLUMN_SALE_QUANTITY = "QUANTITY"
    const val COLUMN_SALE_ACTUALPRICE = "ACTUALPRICE"
    const val COLUMN_SALE_VAT5 = "VAT5"
    const val COLUMN_SALE_NETAMOUNT = "NETAMOUNT"
    const val COLUMN_SALE_BALANCETOPAY = "BALANCETOPAY"

}